/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminBreadcrumb: typeof import('./components/AdminBreadcrumb.vue')['default']
    AdminDrawer: typeof import('./components/AdminDrawer.vue')['default']
    AdminFooter: typeof import('./components/AdminFooter.vue')['default']
    AdminHistoryTab: typeof import('./components/AdminHistoryTab.vue')['default']
    AdminTopbar: typeof import('./components/AdminTopbar.vue')['default']
    AppDrawer: typeof import('./components/AppDrawer.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AuthForm: typeof import('./components/AuthForm.vue')['default']
    CaptchaField: typeof import('./components/CaptchaField.vue')['default']
    ComponentCard: typeof import('./components/ComponentCard.vue')['default']
    ConfirmDeleteDialog: typeof import('./components/ConfirmDeleteDialog.vue')['default']
    CreateAndEditDialog: typeof import('./components/CreateAndEditDialog.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DataTableServer: typeof import('./components/DataTableServer.vue')['default']
    FormDialog: typeof import('./components/FormDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconPicker: typeof import('./components/IconPicker.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    Progress: typeof import('./components/Progress.vue')['default']
    QueryFilters: typeof import('./components/QueryFilters.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerDataTable: typeof import('./components/ServerDataTable.vue')['default']
    StatusEmpty: typeof import('./components/StatusEmpty.vue')['default']
    StatusFailed: typeof import('./components/StatusFailed.vue')['default']
    StatusHandler: typeof import('./components/StatusHandler.vue')['default']
    StatusLoading: typeof import('./components/StatusLoading.vue')['default']
    StatusSuccess: typeof import('./components/StatusSuccess.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
    TreeView: typeof import('./components/TreeView.vue')['default']
    UserProfileMenu: typeof import('./components/UserProfileMenu.vue')['default']
  }
}
