/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminDrawer: typeof import('./components/AdminDrawer.vue')['default']
    AdminFooter: typeof import('./components/AdminFooter.vue')['default']
    AdminTopbar: typeof import('./components/AdminTopbar.vue')['default']
    AppDrawer: typeof import('./components/AppDrawer.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusEmpty: typeof import('./components/StatusEmpty.vue')['default']
    StatusFailed: typeof import('./components/StatusFailed.vue')['default']
    StatusHandler: typeof import('./components/StatusHandler.vue')['default']
    StatusLoading: typeof import('./components/StatusLoading.vue')['default']
    StatusSuccess: typeof import('./components/StatusSuccess.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
  }
}
