/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/': RouteRecordInfo<'/admin/dashboard/', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/analysis/': RouteRecordInfo<'/admin/dashboard/analysis/', '/admin/dashboard/analysis', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/tools/': RouteRecordInfo<'/admin/dashboard/tools/', '/admin/dashboard/tools', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/workplace/': RouteRecordInfo<'/admin/dashboard/workplace/', '/admin/dashboard/workplace', Record<never, never>, Record<never, never>>,
    '/admin/system/': RouteRecordInfo<'/admin/system/', '/admin/system', Record<never, never>, Record<never, never>>,
    '/admin/system/actions/': RouteRecordInfo<'/admin/system/actions/', '/admin/system/actions', Record<never, never>, Record<never, never>>,
    '/admin/system/actions/[id]/': RouteRecordInfo<'/admin/system/actions/[id]/', '/admin/system/actions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/system/cdn/': RouteRecordInfo<'/admin/system/cdn/', '/admin/system/cdn', Record<never, never>, Record<never, never>>,
    '/admin/system/cdn/[id]/': RouteRecordInfo<'/admin/system/cdn/[id]/', '/admin/system/cdn/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/system/menus/': RouteRecordInfo<'/admin/system/menus/', '/admin/system/menus', Record<never, never>, Record<never, never>>,
    '/admin/system/menus/[id]/': RouteRecordInfo<'/admin/system/menus/[id]/', '/admin/system/menus/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/system/roles/': RouteRecordInfo<'/admin/system/roles/', '/admin/system/roles', Record<never, never>, Record<never, never>>,
    '/admin/system/roles/[id]/': RouteRecordInfo<'/admin/system/roles/[id]/', '/admin/system/roles/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/system/users/': RouteRecordInfo<'/admin/system/users/', '/admin/system/users', Record<never, never>, Record<never, never>>,
    '/admin/system/users/[id]/': RouteRecordInfo<'/admin/system/users/[id]/', '/admin/system/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/signin/': RouteRecordInfo<'/auth/signin/', '/auth/signin', Record<never, never>, Record<never, never>>,
    '/auth/signup/': RouteRecordInfo<'/auth/signup/', '/auth/signup', Record<never, never>, Record<never, never>>,
  }
}
